### ISSUE TITLE
'XCTest/XCTest.h' file not found

### ISSUE THREAD

**Issue by inix** [irccloud/ios#191]
open IRCCloud.xcodeproj and compile:
IRCCloudTests/IRCCloudTests.h:9:9: 'XCTest/XCTest.h' file not found

**Comment by c99koder** [comment]
We don't use the tests feature of XCode, so don't try to build the tests

**Comment by inix** [comment]
@c99koder  Do it work that I just delete that folder?

**Comment by c99koder** [comment]
No, just don't build the tests

**Comment by inix** [comment]
@c99koder 
Could you help giving me some tips to exclude building the test directory?
I am a new to ios and not familiar to Xcode yet.
Thanks a lot.

**Comment by c99koder** [comment]
Use the project file included in this repository and build the IRCCloud target, not the tests target.  I would recommend finding some tutorials on how to use XCode, I can't teach you how to use it.

**Comment by inix** [comment]
OK.I got it,thanks

**Comment by inix** [comment]
@c99koder 
I finally delete the tests target and compiled successfully.
Thanks a lot.
