### ISSUE TITLE
Clear push notifications if they've been checked on another device

### ISSUE THREAD

**Issue by pkqk** [irccloud/ios#197]
It appears to be possible now to clear notifications from the lock screen if they've been checked on another device using a silent push notification.

http://stackoverflow.com/questions/21986886/how-does-facebook-messenger-clear-push-notifications-from-the-lock-screen-if-you

**Comment by c99koder** [comment]
Yep, we're planning to support content-available notifications in the future

**Comment by jwheare** [comment]
This should be fixed.
