### ISSUE TITLE
When I "Take a Photo" the camera screen remains black

### ISSUE THREAD

**Issue by jonleung** [irccloud/ios#200]

**Comment by c99koder** [comment]
We're using the standard iOS camera interface.  Check your privacy settings and make sure camera access is enable for the IRCCloud app.  If your phone is jailbroken then try disabling your customizations.

**Comment by jonleung** [comment]
It worked thanks!


—
Sent from my mobile–apologies for brevity and any typos!

hackedu.us | 610-761-0083
