### ISSUE TITLE
Camera issues

### ISSUE THREAD

**Issue by jwheare** [irccloud/ios#226]
Pressing Cancel on the take a photo viewfinder isn't working now.

Also had a report of weird landscape behaviour on an iPhone 6 — IRCCloud/2.1-c7d59ae (iPhone; en-US; iPhone OS 9.2.1)

Here's what they see in the viewfinder:
https://usercontent.irccloud-cdn.com/file/m35sq1qk/IMG_2479.PNG

while the photo it takes is like this:
https://usercontent.irccloud-cdn.com/file/J7ucGOqW/1453580337.JPG

I can't reproduce on my iPhone 6S— IRCCloud/2.1-bdb545e (iPhone; en-GB; iPhone OS 9.2.1), this looks correct to me:
https://usercontent.irccloud-cdn.com/file/zAZQculx/IMG_2043.PNG

**Comment by c99koder** [comment]
Cancel button was fixed in 8de23b1faaccca132d40a3d21026458bd628f8f4
