### ISSUE TITLE
Can't upload from phone

### ISSUE THREAD

**Issue by LukeNZ** [irccloud/ios#237]
iPhone 6+ here. Both taking a photo and choosing a photo won't let me upload anything, I get "Upload Failed An error occured while uploading the file. Please try again."

What's the deal here?

**Comment by c99koder** [comment]
Free accounts are limited to 100MB of file uploads.  Try deleting some of your old uploads to make room for new photos.  You can manage your uploaded files by tapping the upload button and then tapping "File Uploads" from the menu.  In the future, please use the "Send Feedback" menu option or visit our IRC channel instead of GitHub Issues for technical support questions.

**Comment by LukeNZ** [comment]
Right, that makes a lot of sense. However, there should definitely be a more user friendly message for this (especially on mobile) as a I genuinely thought I was encountering a technical issue (which is why I posted here), so I still see this as an issue, just a different one.

**Comment by GaoJunxiao** [comment]
what happend?I don't upload my photo ,but this Email told me I can't upload this And 100MB What？  Are you wrong ?
            在2016年05月14日 20:04，Luke 写道:Right, that makes a lot of sense. However, there should definitely be a more user friendly message for this (especially on mobile) as a I genuinely thought I was encountering a technical issue (which is why I posted here), so I still see this as an issue, just a different one.

**Comment by GaoJunxiao** [comment]
Google Chat?
            在2016年05月14日 20:02，Sam Steele 写道:Free accounts are limited to 100MB of file uploads.  Try deleting some of your old uploads to make room for new photos.  You can manage your uploaded files by tapping the upload button and then tapping "File Uploads" from the menu.  In the future, please use the "Send Feedback" menu option or visit our IRC channel instead of GitHub Issues for technical support questions.

**Comment by orbbfrgg** [comment]
致:GaoJunxiao 先生

对不起，我真不明白你在说什么。

此致
敬礼

orbbfrgg敬上。

**Comment by c99koder** [comment]
Yep, the quota exceeded error message will be implemented in the next update.
