### ISSUE TITLE
the app can not lanuch on simulator with error The operation couldn’t be completed. (LaunchServicesError error 0.)

### ISSUE THREAD

**Issue by flypigrmvb** [irccloud/ios#239]
the app can not lanuch on simulator,
with error below:
The operation couldn’t be completed. (LaunchServicesError error 0.)

**Comment by c99koder** [comment]
Sounds like a problem with XCode on your computer, it works fine for us.  You can find more information in your log file ~/Library/Logs/CoreSimulator/CoreSimulator.log
